package com.hadenwatne.splatbot.enums;

public enum ErrorKeys {
	ALREADY_EXISTS,
	BOT_ERROR,
	CANNOT_DELETE,
	CHANNEL_NOT_FOUND,
	COMMAND_NOT_FOUND,
	HEY_THERE,
	NO_PERMISSION_BOT,
	NO_PERMISSION_USER,
	NOT_FOUND,
	PAGE_NOT_FOUND,
	PERMISSION_MISSING,
	RESERVED_WORD,
	SETTING_VALUE_INVALID,
	WRONG_CHANNEL_TYPE,
	WRONG_USAGE
}