package com.hadenwatne.splatbot.enums;

import com.google.gson.annotations.SerializedName;

public enum LanguageKeys {
    ANARCHY_HEADING,
    DRAW_PROMPT_CHARACTER_ACTION,
    DRAW_PROMPT_CHARACTER_NAME,
    DRAW_PROMPT_ENEMIES,
    DRAW_PROMPT_NOUNS,
    DRAW_PROMPT_VERBS,
    GENERIC_SUCCESS,
    SALMON_RUN_HEADING,
    SETTING_LIST_TITLE,
    SETTING_UPDATED_SUCCESS,
    TIMEZONE_SET,
    TURF_WAR_HEADING,
    WEAPON_SUGGESTIONS
}
