package com.hadenwatne.splatbot.enums;

public enum LanguageKeys {
    ANARCHY_HEADING,
    CHALLENGE_HEADING,
    GENERIC_SUCCESS,
    SALMON_RUN_HEADING,
    SETTING_LIST_TITLE,
    SETTING_UPDATED_SUCCESS,
    SPLATFEST_HEADING,
    TIMEZONE_SET,
    TURF_WAR_HEADING,
    WEAPON_SUGGESTIONS,
    XBATTLES_HEADING,
}
